services:
  # Development services
  postgres:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: intelli_homemaker
      POSTGRES_PASSWORD: "dgeWUgKmRi_nJzovGGRl-s87oB3X1Ylu"
    volumes:
      - intelli_homemaker_data:/var/lib/postgresql/data


  # Test services
  postgres_test:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: intelli_homemaker_test
      POSTGRES_PASSWORD: "1VhD-OXhp_za0kXjJMqtqiQu5RB9INWF"
    volumes:
      - intelli_homemaker_test_data:/var/lib/postgresql/data


volumes:
  intelli_homemaker_data:
  intelli_homemaker_test_data:
